name = "serverless-graphql-server"
type = "webpack"
account_id = "661484bfa811d50ad0a7c946485ad9ae"
workers_dev = true
webpack_config = "webpack.config.js"

[[kv-namespaces]]
name = "TEMPDATA"
binding = "TEMPDATA"
id = "a8a4db8497e241c58cb4f2466bc6b8a4"